export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENT_10 = 'INCREMENT_10';
export const DECREMENT_10 = 'DECREMENT_10';
//  Seo Action types
export const FETCH_SEO_REQUEST = 'FETCH_SEO_REQUEST';
export const FETCH_SEO_SUCCESS = 'FETCH_SEO_SUCCESS';
export const FETCH_SEO_FAILURE = 'FETCH_SEO_FAILURE';
//  Action types for HOME page
//  Latest Action types
export const FETCH_HOME_LATEST_REQUEST = 'FETCH_HOME_LATEST_REQUEST';
export const FETCH_HOME_LATEST_SUCCESS = 'FETCH_HOME_LATEST_SUCCESS';
export const FETCH_HOME_LATEST_FAILURE = 'FETCH_HOME_LATEST_FAILURE';
