//  Seo Action types
export const FETCH_SEO_REQUEST = 'FETCH_SEO_REQUEST';
export const FETCH_SEO_SUCCESS = 'FETCH_SEO_SUCCESS';
export const FETCH_SEO_FAILURE = 'FETCH_SEO_FAILURE';
//  Categories
export const FETCH_CATEGORIES_LIST_REQUEST = 'FETCH_CATEGORIES_LIST_REQUEST';
export const FETCH_CATEGORIES_LIST_SUCCESS = 'FETCH_CATEGORIES_LIST_SUCCESS';
export const FETCH_CATEGORIES_LIST_FAILURE = 'FETCH_CATEGORIES_LIST_FAILURE';
//  Action types for HOME page
//  Latest Action types
export const FETCH_HOME_LATEST_REQUEST = 'FETCH_HOME_LATEST_REQUEST';
export const FETCH_HOME_LATEST_SUCCESS = 'FETCH_HOME_LATEST_SUCCESS';
export const FETCH_HOME_LATEST_FAILURE = 'FETCH_HOME_LATEST_FAILURE';
//  Featured Action types
export const FETCH_HOME_FEATURED_REQUEST = 'FETCH_HOME_FEATURED_REQUEST';
export const FETCH_HOME_FEATURED_SUCCESS = 'FETCH_HOME_FEATURED_SUCCESS';
export const FETCH_HOME_FEATURED_FAILURE = 'FETCH_HOME_FEATURED_FAILURE';
// Posts
export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';

// Posts comments
export const FETCH_POST_COMMENTS_REQUEST = 'FETCH_POST_COMMENTS_REQUEST';
export const FETCH_POST_COMMENTS_SUCCESS = 'FETCH_POST_COMMENTS_SUCCESS';
export const FETCH_POST_COMMENTS_FAILURE = 'FETCH_POST_COMMENTS_FAILURE';
// GoogleMap
export const SHOW_GOOGLE_MARKER_INFO_WINDOW = 'SHOW_GOOGLE_MARKER_INFO_WINDOW';
export const CLOSE_GOOGLE_MARKER_INFO_WINDOW = 'CLOSE_GOOGLE_MARKER_INFO_WINDOW';
// Like/Dislike comments
export const LIKE_COMMENT = 'LIKE_COMMENT';
export const DISLIKE_COMMENT = 'DISLIKE_COMMENT';
