//  Seo Action types
export const FETCH_SEO_REQUEST = 'FETCH_SEO_REQUEST';
export const FETCH_SEO_SUCCESS = 'FETCH_SEO_SUCCESS';
export const FETCH_SEO_FAILURE = 'FETCH_SEO_FAILURE';
//  Categories
export const FETCH_CATEGORIES_LIST_REQUEST = 'FETCH_CATEGORIES_LIST_REQUEST';
export const FETCH_CATEGORIES_LIST_SUCCESS = 'FETCH_CATEGORIES_LIST_SUCCESS';
export const FETCH_CATEGORIES_LIST_FAILURE = 'FETCH_CATEGORIES_LIST_FAILURE';
//  Action types for HOME page
//  Latest Action types
export const FETCH_HOME_LATEST_REQUEST = 'FETCH_HOME_LATEST_REQUEST';
export const FETCH_HOME_LATEST_SUCCESS = 'FETCH_HOME_LATEST_SUCCESS';
export const FETCH_HOME_LATEST_FAILURE = 'FETCH_HOME_LATEST_FAILURE';
//  Featured Action types
export const FETCH_HOME_FEATURED_REQUEST = 'FETCH_HOME_FEATURED_REQUEST';
export const FETCH_HOME_FEATURED_SUCCESS = 'FETCH_HOME_FEATURED_SUCCESS';
export const FETCH_HOME_FEATURED_FAILURE = 'FETCH_HOME_FEATURED_FAILURE';
